owner: fboerman
repo: monitoring

sites:
  - name: Grafana Dashboards
    url: https://data.boerman.dev
  - name: Blog
    url: https://boerman.dev
  - name: Day-Ahead Reports
    url: https://reports.coreflowbased.eu/members/
  - name: Flowbased domain calculators
    url: https://coreflowbased.eu/calculators/
  - name: EU Flow viewer
    url: https://flows.boerman.dev/
  - name: CORE Status Page
    url: https://status.coreflowbased.eu
  - name: Amunanalytics Kratos
    url: https://kratos.coreflowbased.eu/health/alive
    
assignees:
  - fboerman

skipDeleteIssues: true

status-website:
  cname: status.boerman.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Boerman Status Monitoring"
  introTitle: "Status monitoring of websites of boerman.dev and Amun Analytics. Powered by Upptime"
  introMessage: This website shows realtime monitoring info of my personal and business websites
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
